spring:
  datasource:
    url: jdbc:postgresql://${CW_HAPI_DB_HOST}:${CW_HAPI_DB_PORT}/${CW_HAPI_DB_NAME}?currentSchema=${CW_HAPI_DB_SCHEMA_NAME}
    username: ${CW_HAPI_DB_USER_NAME}
    password: ${CW_HAPI_DB_USER_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect

